filters:
  # - upstream: argocd-argocd-server
    # paths: 
    #   - /applications/argocd/ingress-nginx?resource=
  # - upstream: ""
  #   paths:
  #     - /ws/ResearchOutputService
  #     - /portal-rest/