apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-traffic-stats
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
