apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-traffic-stats
subjects:
  - kind: ServiceAccount
    name: nginx-traffic-stats
roleRef:
  kind: Role
  name: nginx-traffic-stats
  apiGroup: rbac.authorization.k8s.io
