kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: a-simple-pipeline
spec:
  tasks:
  - name: task-1
    taskSpec:
      steps:
      - image: alpine:3.15
        script: |
          echo "hello"